# This configuration file defines global settings for test execution.
# The test suite will attempt to apply these settings to all tests that
# support them.

# Global settings
global-settings:
    # The active test configuration.  The value must match a subsequent key
    # in this file, which defines the global settings to apply to the test execution
    # run.
    test-configuration: config-standard

    # The following sequence defines for any test configuration the available pre-
    # and post-test conditions.  The 'name' field specifies how the test configurations
    # refer to the pre- and post-test conditions in order to activate them.
    condition-definitions:
            -
                name: 'threads'
                pre:
                    typename: 'asterisk.thread_test_condition.ThreadPreTestCondition'
                post:
                    typename: 'asterisk.thread_test_condition.ThreadPostTestCondition'
                    related-type: 'asterisk.thread_test_condition.ThreadPreTestCondition'
            -
                name: 'sip-dialogs'
                pre:
                    typename: 'asterisk.sip_dialog_test_condition.SipDialogPreTestCondition'
                post:
                    typename: 'asterisk.sip_dialog_test_condition.SipDialogPostTestCondition'
            -
                name: 'locks'
                pre:
                    typename: 'asterisk.lock_test_condition.LockTestCondition'
                post:
                    typename: 'asterisk.lock_test_condition.LockTestCondition'
            -
                name: 'file-descriptors'
                pre:
                    typename: 'asterisk.fd_test_condition.FdPreTestCondition'
                post:
                    typename: 'asterisk.fd_test_condition.FdPostTestCondition'
                    related-type: 'asterisk.fd_test_condition.FdPreTestCondition'
            -
                name: 'channels'
                pre:
                    typename: 'asterisk.channel_test_condition.ChannelTestCondition'
                post:
                    typename: 'asterisk.channel_test_condition.ChannelTestCondition'
            -
                name: 'sip-channels'
                pre:
                    typename: 'asterisk.sip_channel_test_condition.SipChannelTestCondition'
                post:
                    typename: 'asterisk.sip_channel_test_condition.SipChannelTestCondition'

# Exclude all long-running tests (greater than one minute)
config-fast:
    exclude-tests:
        - 'authenticate_invalid_password'
        - 'check_voicemail_callback'
        - 'check_voicemail_delete'
        - 'check_voicemail_dialout'
        - 'check_voicemail_envelope'
        - 'check_voicemail_new_user'
        - 'check_voicemail_nominal'
        - 'check_voicemail_reply'
        - 'leave_voicemail_external_notification'
        - 'leave_voicemail_nominal'
        - 'gateway_g711_t38'
        - 'gateway_mix1'
        - 'gateway_mix2'
        - 'gateway_mix3'
        - 'gateway_mix4'
        - 'gateway_native_t38'
        - 'gateway_native_t38_ced'
        - 'gateway_no_t38'
        - 'gateway_t38_g711'
        - 'gateway_timeout1'
        - 'gateway_timeout2'
        - 'gateway_timeout3'
        - 'gateway_timeout4'
        - 'gateway_timeout5'

# Include all tests that can run under the installed version of Asterisk.
# It is included merely for completeness.
config-standard:

# This test enables the pre- and post-test condition checking on all tests
# that support it.  Individual tests can override the behavior of a pre-
# and post-test in their test-config.yaml files.
config-pessimistic:
    properties:
        testconditions:
            - name: 'threads'
            - name: 'sip-dialogs'
            - name: 'locks'
            - name: 'file-descriptors'
            - name: 'channels'
            - name: 'sip-channels'

config-specific-version:
    properties:
        # Override the version of Asterisk under test to the specified version.
        # This is particularly useful if the version under test is from a team
        # branch not based on Asterisk trunk.
        forced-version: 1.8.0.0

